apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-script
spec:
  description: Read and display script.
  workspaces:
  - name: source
  steps:
  - name: read
    image: ubuntu 
    script: | 
      #!/usr/bin/env  bash
      cd $(workspaces.source.path) && ls -alt
      chmod 755 installAWSCLI.sh
      pwd
      ls -alt
      $(workspaces.source.path)/installAWSCLI.sh  -i <ACCESS_KEY> -s <SECRET_ACCESS_KEY>
