apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: show-script-secret
spec:
  description: Read and display script.
  workspaces:
  - name: source
  steps:
  - name: read
    image: ubuntu 
    script: | 
      #!/usr/bin/env  bash
      cd $(workspaces.source.path) && ls -alt
