apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: apply-terraform-pipeline-run
spec:
  pipelineRef:
    name: apply-terraform-pipeline
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: git-credentials
    secret:
      secretName: git-credentials
  params:
  - name: repo-url
    value: git@github.ibm.com:instana/qa-enablement.git
