apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: apply-terraform-pipeline
spec:
  params:
  - name: team-automation-repo-url
    type: string
  - name: performance-team-repo-url
    type: string
  - name: config
    type: string
  workspaces:
  - name:  team-automation-code
    description: | 
      This workspace contains the cloned team automation repo files
  - name:  performance-team-code
    description: | 
      This workspace contains the cloned performance team  repo files
  - name: git-credentials
    description: My ssh credentials
  tasks:
  - name: clone-team-automation-code
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: team-automation-code
    - name: ssh-directory
      workspace: git-credentials
    params:
    - name: url
      value: $(params.team-automation-repo-url)
  - name: clone-performance-team-code
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: performance-team-code
    - name: ssh-directory
      workspace: git-credentials
    params:
    - name: url
      value: $(params.performance-team-repo-url)        
  - name: apply-terraform-task
    runAfter: ["clone-team-automation-code","clone-performance-team-code"]
    taskRef:
      name: apply-terraform-task 
    workspaces:
    - name: team-automation-code 
      workspace: team-automation-code
    - name: performance-team-code
      workspace: performance-team-code
    params:
    - name: config
      value: $(params.config)
